import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header className="bg-white shadow-md">
          <nav className="container mx-auto flex justify-between items-center py-4 px-6">
            <div>
              <h1 className="text-2xl font-bold text-red-700">
                L'Observatoire du Syntaxerrorisme
              </h1>
              <p className="text-black">
                la référence mondiale du syntaxerrorisme
              </p>
            </div>
            <ul className="flex gap-6 text-sm sm:text-base">
              <li>
                <a href="/laws" className="text-black hover:text-red-600">
                  Juridique
                </a>
              </li>
              <li>
                <a href="/history" className="text-black hover:text-red-600">
                  Histoire
                </a>
              </li>
              <li>
                <a href="/medias" className="text-black hover:text-red-600">
                  Médias
                </a>
              </li>
              <li>
                <a href="/portraits" className="text-black hover:text-red-600">
                  Portraits
                </a>
              </li>
              <li>
                <a href="/games" className="text-black hover:text-red-600">
                  Jeux
                </a>
              </li>
              <li>
                <a href="/about" className="text-black hover:text-red-600">
                  A propos
                </a>
              </li>
            </ul>
          </nav>
        </header>

        {children}

        {/* Footer */}
        <footer className="bg-gray-100 border-t py-12 text-sm text-gray-600">
          <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-4 gap-8 text-left">
            {/* Bloc 1 : Présentation */}
            <div>
              <h3 className="font-semibold text-gray-800 mb-3">
                Observatoire du Syntaxerrorisme
              </h3>
              <p className="mb-3">
                L’Observatoire du Syntaxerrorisme documente et analyse le crime
                de
                <strong> syntaxerrorisme</strong> à travers ses aspects
                juridiques, historiques, médiatiques et humains. Notre mission :
                informer, prévenir et sensibiliser.
              </p>
              <p className="text-xs text-gray-500">
                © {new Date().getFullYear()} Observatoire du Syntaxerrorisme —
                Tous droits réservés
              </p>
            </div>

            {/* Bloc 2 : Juridique */}
            <div>
              <h4 className="font-semibold text-gray-800 mb-2">Juridique</h4>
              <ul className="space-y-1">
                <li>
                  <a href="/juridique/laws" className="hover:underline">
                    Textes de lois
                  </a>
                </li>
                <li>
                  <a
                    href="/juridique/jurisprudence"
                    className="hover:underline"
                  >
                    Jurisprudence
                  </a>
                </li>
                <li>
                  <a href="/juridique/penalcode" className="hover:underline">
                    Code pénal
                  </a>
                </li>
                <li>
                  <a href="/juridique/procedure" className="hover:underline">
                    Procédure
                  </a>
                </li>
                <li>
                  <a href="/juridique/prevention" className="hover:underline">
                    Prévention
                  </a>
                </li>
              </ul>
            </div>

            {/* Bloc 3 : Histoire & Médias */}
            <div>
              <h4 className="font-semibold text-gray-800 mb-2">Histoire</h4>
              <ul className="space-y-1 mb-4">
                <li>
                  <a href="/history" className="hover:underline">
                    Introduction
                  </a>
                </li>
                <li>
                  <a href="/history/chronology" className="hover:underline">
                    Chronologie
                  </a>
                </li>
                <li>
                  <a href="/history/figures" className="hover:underline">
                    Figures marquantes
                  </a>
                </li>
              </ul>
              <h4 className="font-semibold text-gray-800 mb-2">Médias</h4>
              <ul className="space-y-1">
                <li>
                  <a href="/medias/articles" className="hover:underline">
                    Articles
                  </a>
                </li>
                <li>
                  <a href="/medias/bibliography" className="hover:underline">
                    Bibliographie
                  </a>
                </li>
                <li>
                  <a href="/medias/movies" className="hover:underline">
                    Films & documentaires
                  </a>
                </li>
              </ul>
            </div>

            {/* Bloc 4 : Portraits, Jeux, À propos */}
            <div>
              <h4 className="font-semibold text-gray-800 mb-2">Portraits</h4>
              <ul className="space-y-1 mb-4">
                <li>
                  <a href="/portraits/convicted" className="hover:underline">
                    Condamnés
                  </a>
                </li>
                <li>
                  <a href="/portraits/lawyers" className="hover:underline">
                    Avocats
                  </a>
                </li>
                <li>
                  <a href="/portraits/political" className="hover:underline">
                    Politiques
                  </a>
                </li>
                <li>
                  <a href="/portraits/victims" className="hover:underline">
                    Victimes
                  </a>
                </li>
              </ul>
              <h4 className="font-semibold text-gray-800 mb-2">Jeux</h4>
              <ul className="space-y-1 mb-4">
                <li>
                  <a href="/games/quizz" className="hover:underline">
                    Quiz
                  </a>
                </li>
                <li>
                  <a href="/games/topten" className="hover:underline">
                    Top 10
                  </a>
                </li>
              </ul>
              <h4 className="font-semibold text-gray-800 mb-2">À propos</h4>
              <ul className="space-y-1">
                <li>
                  <a href="/about/contact" className="hover:underline">
                    Contact
                  </a>
                </li>
                <li>
                  <a href="/about/faq" className="hover:underline">
                    FAQ
                  </a>
                </li>
                <li>
                  <a href="/about/lexicon" className="hover:underline">
                    Lexique
                  </a>
                </li>
              </ul>
            </div>
          </div>

          {/* Bas de page SEO */}
          <div className="mt-8 text-center text-xs text-gray-500 max-w-5xl mx-auto px-4">
            <p>
              Mots-clés liés : syntaxerrorisme, crime syntaxique, droit
              numérique, jurisprudence web, prévention des erreurs de syntaxe,
              histoire du syntaxerrorisme, figures marquantes, victimes, avocats
              spécialisés, observatoire numérique, code pénal fictif.
            </p>
            <p className="mt-2">
              <a href="/mentions-legales" className="hover:underline">
                Mentions légales
              </a>{" "}
              ·
              <a
                href="/politique-de-confidentialite"
                className="hover:underline ml-2"
              >
                Politique de confidentialité
              </a>{" "}
              ·
              <a href="/plan-du-site" className="hover:underline ml-2">
                Plan du site
              </a>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}

/*
home
-Juridique (laws)
--(jurisprudence)
--(penalcode)
--prevention)
--(procedure)
-Histoire (history)
--(chronology)
--(figures)
-Médias (medias)
--(articles)
--(bibliography)
--(movies)
-Portraits (portraits)
--(convicted)
--(lawyers)
--(political)
--(victims)
-Jeux (games)
--(quizz)
--(topten)
-A propos (about)
--(contact)
--(faq)
--(lexicon)
*/
